settings:
  commit_msg: "⚡ Update README with the recent activity"
  max_lines: 8
  disabled_events:
    - "push"
    - "review"
    - "star"
    - "comments"
    - "fork"
  ignored_repos: [WeixuanZ/flood-warning-system]
  date:
    timezone: "Europe/London"
